apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: document-compliance
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgresql+asyncpg://docadmin:docpass123@postgres-service:5432/document_compliance"
